name: nature_vista
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  video_player: ^2.5.0          # latest stable
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.0
  fullscreen_window: ^1.0.0
  path_provider: ^2.1.5
  media_kit: ^1.2.1
  media_kit_video: ^1.3.1
  media_kit_libs_windows_video: ^1.0.4  
  media_kit_libs_video: ^1.0.4
  flutter_vlc_player: ^7.4.2
  flutter_inappwebview: ^6.0.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shared_preferences: ^2.5.3
  pdfrx: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/www/
    - assets/www/data/
    - assets/www/data/111111111/
    - assets/www/data/111111111/old/
    - assets/www/flipbook/
    - assets/www/flipbook/css/
    - assets/www/flipbook/extras/
    - assets/www/flipbook/files/
    - assets/www/flipbook/files/backgrounds/
    - assets/www/flipbook/js/
    - assets/www/flipbook/lib/
    - assets/www/flipbook/pics/
    - assets/images/
    - assets/images/location.mp4
    - assets/gallery/
    - assets/amenities/
    - assets/audio/
    - assets/plans/
    - assets/logo/
    - assets/pdf/
    - assets/newback/plansbackgraund.png
    - assets/newback/tourbackgaund.png
    - assets/buildingone/
    - assets/buildingtwo/
    - assets/NV_1st_launch/
    - assets/build/
    - assets/tourvideo/wolkthrow.mp4
    - assets/tourvideo/